### ISSUE TITLE
链接有问题

### ISSUE THREAD

**Issue by chengwentao1** [fuchengjie/WebSSH#2]
### 你前端的his._generateEndpoint()方法返回的是ip加没有端口所以你那边长链接会失败，所以返回的数据的时候要不把getIp返回数据的时候要不把配置文件的端口读取下

**Comment by fuchengjie** [comment]
能否具体描述下解决方案？端口指的是websocket还是什么？因为我这里没出现链接的问题，所以不太能定位。

**Comment by endlesshh** [comment]
var endpoint = protocol + window.location.host + '/webssh'; 不要使用服务器ip，直接获取当前网页的域名或者ip+端口。同时springboot的websocket和web的端口公用。会更加省事一下

**Comment by chengwentao1** [comment]
> var endpoint = protocol + window.location.host + '/webssh'; 不要使用服务器ip，直接获取当前网页的域名或者ip+端口。同时springboot的websocket和web的端口公用。会更加省事一下
正解

**Comment by fuchengjie** [comment]
你好，相关代码提交了
